### ISSUE TITLE
Acquirement for grammaticality model

### ISSUE THREAD

**Issue by y1ny** [stevenxcao/constituency-test-parser#3]
Hi, great job! I would like to test a few sentences using your constituency test parser. However, I noticed that you haven't uploaded the grammatical model. Training the model from scratch is quite time-consuming. Have you considered uploading the grammatical model (before and after refinement) anytime soon? Thanks!

**Comment by stevenxcao** [comment]
Hi! Please feel free to email me and I can send you the model.

**Comment by y1ny** [comment]
thx! I have sent an email to the address you provided in your paper.
